# Generated by Django 6.0.6 on 2026-06-20 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=512)),
                ('address2', models.CharField(blank=True, max_length=512)),
                ('city', models.CharField(max_length=255)),
                ('state_region', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(default='Rwanda', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=5000, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('contact_full_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('ship_full_name', models.CharField(blank=True, max_length=255)),
                ('ship_address1', models.CharField(blank=True, max_length=512)),
                ('ship_address2', models.CharField(blank=True, max_length=512)),
                ('ship_city', models.CharField(blank=True, max_length=255)),
                ('ship_state_region', models.CharField(blank=True, max_length=255)),
                ('ship_postal_code', models.CharField(blank=True, max_length=50)),
                ('ship_country', models.CharField(blank=True, default='Rwanda', max_length=100)),
                ('ship_instructions', models.TextField(blank=True)),
                ('payment_brand', models.CharField(blank=True, max_length=50)),
                ('payment_last4', models.CharField(blank=True, max_length=4)),
                ('payment_expiry', models.CharField(blank=True, max_length=10)),
                ('payment_holder', models.CharField(blank=True, max_length=255)),
                ('payment_label', models.CharField(blank=True, max_length=255)),
                ('payment_status', models.CharField(blank=True, default='Payment details received', max_length=100)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=512)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('price_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image', models.TextField(blank=True)),
                ('page', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='card', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('last4', models.CharField(max_length=4)),
                ('expiry_month', models.CharField(max_length=2)),
                ('expiry_year', models.CharField(max_length=4)),
                ('expiry_label', models.CharField(blank=True, max_length=10)),
                ('holder_name', models.CharField(max_length=255)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_phone', models.CharField(blank=True, max_length=50)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=512)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('price_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image', models.TextField(blank=True)),
                ('page', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'product_id')},
            },
        ),
    ]
